name: Deploy Frontend to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use a valid Node.js version

      - name: Install Dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Transfer files to Remote Server
        uses: easingthemes/ssh-deploy@main
        with:
          SOURCE : frontend/
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          EXCLUDE: "/.next/, /node_modules/"
          TARGET: /home/ubuntu/code/  # Specify the target directory on the remote server

      - name: SSH into Remote Server and Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/code/frontend
            echo "brought here by github" > /home/ubuntu/command.txt
